package org.study;

import org.junit.jupiter.api.Test;

public class MainTest {

    @Test
    void Testexception(){
        try {
                    int ary[] = {1,2,5,6,7,8};
                    for (int i=0;i<=ary.length;i++){
                        System.out.println(ary[i]);
                    }
                }
                catch (Exception e){
                    System.out.println("\nException caught");
                }

            }


        }

